name: Deploy to EC2

on:
  push:
    branches:
      - ft-rework

jobs:
  deploy:
    if: github.repository == 'simple-works/ACT'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          command_timeout: "20m"
          script: |
            cd /home/ubuntu/ACT/
            git fetch fork ft-rework
            git reset --hard fork/ft-rework
            sudo systemctl restart act-app.service
            sleep 3
            sudo systemctl status act-app.service --no-pager
