name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    if: github.repository == 'simple-works/ACT'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          command_timeout: "20m"
          script: |
            APP_DIR="/home/ubuntu/ACT"
            REPO_URL="https://github.com/simple-works/ACT.git"
            REMOTE="fork"
            BRANCH="main"

            if [ ! -d "$APP_DIR" ]; then
              echo "Directory $APP_DIR does not exist. Creating and cloning..."
              mkdir -p "$APP_DIR"
              cd "$APP_DIR"
              git clone --depth 1 "$REPO_URL" .
              git checkout "$BRANCH"
            else
              cd "$APP_DIR"
              if [ ! -d ".git" ]; then
                echo "No git repo found, Re-cloning..."
                rm -rf *
                git clone --depth 1 "$REPO_URL" .
                git checkout "$BRANCH"
              else
                echo "Fetching and resetting..."
                git fetch "$REMOTE" "$BRANCH"
                git reset --hard "$REMOTE"/"$BRANCH"
              fi
            fi

            echo "Restarting service..."
            sudo systemctl restart act-app.service
            sleep 3
            sudo systemctl status act-app.service --no-pager
