name: Deploy to EC2

on:
  push:
    branches:
      - ft-rework

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            pkill -f "uv"
            cd /home/ubuntu/TACT/
            git pull fork ft-rework
            nohup uv run task app-prod &
